# Generated by Django 4.2.2 on 2023-07-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek_literacki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(4, 'thriller'), (6, 'popularno-naukowa'), (2, 'kryminał'), (8, 'naukowa'), (7, 'komedia'), (0, 'inne'), (3, 'przygodowa'), (9, 'podróżnicza'), (5, 'obyczajowa'), (1, 'powieść'), (10, 'reportaż')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okladka', models.ImageField(blank=True, null=True, upload_to='plakaty')),
                ('tytul', models.CharField(blank=True, max_length=64, unique=True)),
                ('autor', models.CharField(max_length=72)),
                ('rok_wydania', models.PositiveSmallIntegerField(default=2000)),
                ('wydawnictwo', models.CharField(max_length=64, unique=True)),
                ('opis', models.TextField(default='')),
                ('gatunek', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_init_1.gatunek_literacki')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_init_1.ksiazka')),
            ],
        ),
        migrations.CreateModel(
            name='Pisarz',
            fields=[
                ('autor', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='books_init_1.ksiazka')),
                ('biogram', models.TextField(default='')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='zdjecia')),
                ('tytul', models.ManyToManyField(related_name='+', to='books_init_1.ksiazka')),
            ],
        ),
    ]
